apiVersion: apps/v1
kind: Deployment
metadata:
  name: signon
  labels:
    app: signon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signon
  template:
    metadata:
      labels:
        app: signon
    spec:
      containers:
      - name: signon
        image: JSVAR_DOCKERIMAGE
---        
apiVersion: v1
kind: Service
metadata:
  name: signon-service
spec:
  type: NodePort
  selector:
    app: signon
  ports:
  - protocol: TCP
    port: 80
  
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: signon-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /signon/(.*)
          backend:
            serviceName: signon-service
            servicePort: 80        
